/** Tripwire orchestration — runs bytecode VM and compares against normal JS */

import type { AggregateFeatures } from '../../server/types';
import { decode } from './decoder';
import { execute } from './interpreter';
import { createBioBridge } from './bridge';
import type { BridgeContext } from './bridge';

// Lazy-loaded generated bytecode (may not exist before first compile)
let bytecodeCache: { bytecode: string; key: string; secret: string } | null = null;

async function loadBytecodeModules() {
  if (bytecodeCache) return bytecodeCache;
  try {
    const mod = await import('./bytecode-modules');
    bytecodeCache = {
      bytecode: mod.TRIPWIRE_BYTECODE,
      key: mod.TRIPWIRE_KEY,
      secret: mod.DEPLOY_SECRET,
    };
    return bytecodeCache;
  } catch {
    return null;
  }
}

function hexToBytes(hex: string): Uint8Array {
  const bytes = new Uint8Array(hex.length / 2);
  for (let i = 0; i < hex.length; i += 2) {
    bytes[i / 2] = parseInt(hex.slice(i, i + 2), 16);
  }
  return bytes;
}

function xorDescramble(data: Uint8Array, key: Uint8Array): Uint8Array {
  const result = new Uint8Array(data.length);
  for (let i = 0; i < data.length; i++) {
    result[i] = data[i] ^ key[i % key.length];
  }
  return result;
}

function base64ToBytes(b64: string): Uint8Array {
  const binaryStr = atob(b64);
  const bytes = new Uint8Array(binaryStr.length);
  for (let i = 0; i < binaryStr.length; i++) {
    bytes[i] = binaryStr.charCodeAt(i);
  }
  return bytes;
}

export interface TripwireResult {
  tampered: boolean;
  vmSignals: string[];
  vmIntegrityHash: string;
}

/** Poison features to look like a natural bot submission */
export function immolateFeatures(features: AggregateFeatures): AggregateFeatures {
  return {
    ...features,
    zeroMovementRatio: 0.95,
    avgTimestampDelta: 0.3,
    coalescedRatio: 0,
    tremorRatio: 0.02,
    powerLawBeta: 0.05,
    rafCadenceRatio: 0.2,
  };
}

interface Stroke {
  points: {
    x: number;
    y: number;
    t: number;
    coalescedCount: number;
    movementX: number;
    movementY: number;
  }[];
}

/**
 * Run the tripwire VM. Call after computeFeatures() and detectTampering()/detectCDP().
 *
 * If the VM detects tampering (its readings disagree with normal JS),
 * it returns tampered=true with the signals it found.
 */
export async function runTripwire(
  strokes: Stroke[],
  features: AggregateFeatures
): Promise<TripwireResult> {
  const fallback: TripwireResult = { tampered: false, vmSignals: [], vmIntegrityHash: '' };

  const modules = await loadBytecodeModules();
  if (!modules) return fallback;

  try {
    // Descramble bytecode
    const scrambled = base64ToBytes(modules.bytecode);
    const key = hexToBytes(modules.key);
    const binary = xorDescramble(scrambled, key);

    // Decode bytecode module
    const mod = decode(binary.buffer as ArrayBuffer);

    // Create bridge with current context
    let immolateSignals: string[] | null = null;
    const ctx: BridgeContext = {
      getStrokes: () => strokes,
      getFeatures: () => features,
      onImmolate: (signals) => {
        immolateSignals = signals;
      },
    };
    const bridge = createBioBridge(ctx);

    // Execute bytecode
    const result = execute(mod, bridge);

    // Parse result from R0
    const vmResult = result.value as
      | {
          tampered: boolean;
          signals: string[];
          hash: string;
        }
      | undefined;

    if (!vmResult) return fallback;

    return {
      tampered: vmResult.tampered || immolateSignals !== null,
      vmSignals: immolateSignals ?? vmResult.signals,
      vmIntegrityHash: vmResult.hash,
    };
  } catch {
    // VM execution failed — don't break the main flow
    return fallback;
  }
}
