/**
 * Compile tripwire detection program to bytecode.
 *
 * Usage: npx tsx scripts/compile-tripwire.ts [--key <hex>]
 *
 * Reads scripts/tripwire-src/detect.ts (JS subset)
 * Compiles to BytecodeModule via forked compiler + acorn
 * Encodes to binary
 * XOR-scrambles with build-time key
 * Writes src/vm/bytecode-modules.ts (generated, gitignored)
 */

import * as fs from 'node:fs';
import * as path from 'node:path';
import * as crypto from 'node:crypto';
import { compile } from './compiler/index';
import { encode } from './compiler/encoder';

const ROOT = path.resolve(import.meta.dirname, '..');
const DETECT_SRC = path.join(ROOT, 'scripts/tripwire-src/detect.ts');
const OUTPUT = path.join(ROOT, 'src/vm/bytecode-modules.ts');

// Parse CLI args for --key
function parseKey(): Buffer {
  const idx = process.argv.indexOf('--key');
  if (idx !== -1 && process.argv[idx + 1]) {
    return Buffer.from(process.argv[idx + 1], 'hex');
  }
  // Generate random 32-byte key
  return crypto.randomBytes(32);
}

function xorScramble(data: Uint8Array, key: Buffer): Uint8Array {
  const result = new Uint8Array(data.length);
  for (let i = 0; i < data.length; i++) {
    result[i] = data[i] ^ key[i % key.length];
  }
  return result;
}

function main() {
  console.log('[compile-tripwire] Reading source...');
  const source = fs.readFileSync(DETECT_SRC, 'utf-8');

  // Strip TypeScript-specific syntax (the detect.ts is a JS subset)
  // Remove any type annotations if present
  const jsSource = source
    .replace(/\/\/\s*@ts-nocheck.*\n?/g, '')
    .replace(/^\s*\/\/.*$/gm, (line) => line); // keep comments

  console.log('[compile-tripwire] Compiling...');
  const module = compile(jsSource);
  console.log(
    `[compile-tripwire] Compiled: ${module.code.length} instructions, ` +
      `${module.strings.length} strings, ${module.apiTable.length} API entries`
  );

  console.log('[compile-tripwire] Encoding to binary...');
  const binary = encode(module);
  const bytes = new Uint8Array(binary);
  console.log(`[compile-tripwire] Binary size: ${bytes.length} bytes`);

  console.log('[compile-tripwire] XOR scrambling...');
  const key = parseKey();
  const scrambled = xorScramble(bytes, key);

  // Generate deploy secret (embedded in bytecode for integrity hash)
  const deploySecret = crypto.randomBytes(16).toString('hex');

  // Write output as TypeScript module
  const b64 = Buffer.from(scrambled).toString('base64');
  const keyHex = key.toString('hex');

  const output = `// Auto-generated by scripts/compile-tripwire.ts — DO NOT EDIT
// Generated: ${new Date().toISOString()}

/** XOR-scrambled bytecode (base64) */
export const TRIPWIRE_BYTECODE = '${b64}';

/** XOR key (hex) */
export const TRIPWIRE_KEY = '${keyHex}';

/** Deploy-time secret for integrity hash */
export const DEPLOY_SECRET = '${deploySecret}';
`;

  fs.writeFileSync(OUTPUT, output, 'utf-8');
  console.log(`[compile-tripwire] Written to ${path.relative(ROOT, OUTPUT)}`);
  console.log(`[compile-tripwire] Deploy secret: ${deploySecret.slice(0, 8)}...`);
}

main();
