// scripts/generate-sbox.ts
// Generate a 256-byte S-box (substitution table) and its inverse.
// Run with: npx tsx scripts/generate-sbox.ts
//
// Output: src/utils/sbox.ts and server/sbox.ts
// The S-box is applied BEFORE AES-GCM encryption (server side) and
// reversed AFTER AES-GCM decryption (client side) as an obfuscation layer.

import { writeFileSync } from 'fs';
import { resolve, dirname } from 'path';
import { fileURLToPath } from 'url';
import { randomBytes } from 'crypto';

const __dirname = dirname(fileURLToPath(import.meta.url));

// Fisher-Yates shuffle with crypto-secure random
function generateSbox(): number[] {
  const sbox = Array.from({ length: 256 }, (_, i) => i);
  for (let i = 255; i > 0; i--) {
    // Crypto-secure random index in [0, i]
    const rand = randomBytes(4).readUInt32BE(0);
    const j = rand % (i + 1);
    [sbox[i], sbox[j]] = [sbox[j], sbox[i]];
  }
  return sbox;
}

function invertSbox(sbox: number[]): number[] {
  const inv = new Array(256);
  for (let i = 0; i < 256; i++) {
    inv[sbox[i]] = i;
  }
  return inv;
}

function formatArray(arr: number[], name: string): string {
  const lines: string[] = [];
  lines.push(`export const ${name}: readonly number[] = [`);
  for (let i = 0; i < arr.length; i += 16) {
    const chunk = arr.slice(i, i + 16);
    lines.push('  ' + chunk.map((v) => String(v).padStart(3, ' ')).join(',') + ',');
  }
  lines.push('];');
  return lines.join('\n');
}

const sbox = generateSbox();
const sboxInv = invertSbox(sbox);

const fileContent = `// Auto-generated by scripts/generate-sbox.ts — DO NOT EDIT
// 256-byte substitution table for obfuscation layer (applied before/after AES-GCM)

${formatArray(sbox, 'SBOX')}

${formatArray(sboxInv, 'SBOX_INV')}

/** Apply S-box substitution to each byte (server encryption side) */
export function sboxApply(data: Uint8Array): Uint8Array {
  const out = new Uint8Array(data.length);
  for (let i = 0; i < data.length; i++) {
    out[i] = SBOX[data[i]];
  }
  return out;
}

/** Reverse S-box substitution (client decryption side) */
export function sboxReverse(data: Uint8Array): Uint8Array {
  const out = new Uint8Array(data.length);
  for (let i = 0; i < data.length; i++) {
    out[i] = SBOX_INV[data[i]];
  }
  return out;
}
`;

// Write to both client and server
writeFileSync(resolve(__dirname, '../src/utils/sbox.ts'), fileContent);
writeFileSync(resolve(__dirname, '../server/sbox.ts'), fileContent);

console.log('Generated src/utils/sbox.ts and server/sbox.ts');
