// scripts/generate-masks.ts
// Generate 1-bit packed glyph masks for server-side challenge rendering.
// Run with: npx tsx scripts/generate-masks.ts
//
// Uses @napi-rs/canvas (devDependency only — not needed at runtime).
// Output: server/glyph-masks.ts
//
// Generates multiple font variants per glyph for dynamic mask selection.

import { writeFileSync } from 'fs';
import { resolve, dirname } from 'path';
import { fileURLToPath } from 'url';
import { createCanvas } from '@napi-rs/canvas';

const __dirname = dirname(fileURLToPath(import.meta.url));

const MASK_W = 64;
const MASK_H = 48;

// Same glyph set as useChallenge.ts FALLBACK_LETTERS (letters only, see that file for exclusion notes)
// jscpd:ignore-start
const GLYPHS = [
  'A',
  'B',
  'C',
  'E',
  'F',
  'G',
  'H',
  'I',
  'J',
  'K',
  'L',
  'M',
  'N',
  'O',
  'P',
  'R',
  'S',
  'T',
  'U',
  'W',
  'X',
  'Y',
  'Z',
];
// jscpd:ignore-end

// Font variants — distinct families produce structurally different letterforms.
// Each entry: [fontSpec, yOffset] to account for baseline differences.
const FONT_VARIANTS: [string, number][] = [
  [`900 ${MASK_H * 0.72}px "DejaVu Sans"`, 1],
  [`900 ${MASK_H * 0.72}px "DejaVu Serif"`, 1],
  [`900 ${MASK_H * 0.72}px "Liberation Sans"`, 1],
  [`900 ${MASK_H * 0.72}px "Liberation Serif"`, 1],
  [`900 ${MASK_H * 0.72}px "FreeSans"`, 1],
  [`900 ${MASK_H * 0.72}px "FreeSerif"`, 1],
  [`900 ${MASK_H * 0.72}px "Courier 10 Pitch"`, 1],
  [`italic 900 ${MASK_H * 0.72}px "DejaVu Sans"`, 1],
];

function renderMask(char: string, font: string, yOffset: number): string {
  const canvas = createCanvas(MASK_W, MASK_H);
  const ctx = canvas.getContext('2d');

  ctx.fillStyle = '#000';
  ctx.fillRect(0, 0, MASK_W, MASK_H);

  ctx.fillStyle = '#fff';
  ctx.font = font;
  ctx.textAlign = 'center';
  ctx.textBaseline = 'middle';
  ctx.fillText(char, MASK_W / 2, MASK_H / 2 + yOffset);

  const imageData = ctx.getImageData(0, 0, MASK_W, MASK_H);
  const totalPixels = MASK_W * MASK_H;
  const bytes = new Uint8Array(Math.ceil(totalPixels / 8));

  for (let i = 0; i < totalPixels; i++) {
    if (imageData.data[i * 4] > 128) {
      bytes[Math.floor(i / 8)] |= 1 << (7 - (i % 8));
    }
  }

  return Buffer.from(bytes).toString('base64');
}

// Generate all variants
const variants: Record<string, string[]> = {};
for (const g of GLYPHS) {
  variants[g] = [];
  for (const [font, yOffset] of FONT_VARIANTS) {
    variants[g].push(renderMask(g, font, yOffset));
  }
}

// Deduplicate variants per glyph (some fonts may render identically)
for (const g of GLYPHS) {
  variants[g] = [...new Set(variants[g])];
}

// First variant of each = default (backward-compatible GLYPH_MASKS)
const defaultMasks: Record<string, string> = {};
for (const g of GLYPHS) {
  defaultMasks[g] = variants[g][0];
}

// Output TypeScript file
const output = `// Auto-generated by scripts/generate-masks.ts — DO NOT EDIT
// ${MASK_W}x${MASK_H} 1-bit packed masks for glyph display (base64-encoded)
// Regenerate with: npx tsx scripts/generate-masks.ts

export const MASK_WIDTH = ${MASK_W};
export const MASK_HEIGHT = ${MASK_H};

/** Map from glyph character → array of font variant masks (base64-encoded 1-bit packed) */
export const GLYPH_VARIANTS: Record<string, string[]> = ${JSON.stringify(variants, null, 2)};

/** Default mask per glyph (first variant) — backward compatible */
export const GLYPH_MASKS: Record<string, string> = ${JSON.stringify(defaultMasks, null, 2)};
`;

const outPath = resolve(__dirname, '../server/glyph-masks.ts');
writeFileSync(outPath, output, 'utf-8');

let totalVariants = 0;
for (const g of GLYPHS) {
  totalVariants += variants[g].length;
}
console.log(
  `Wrote ${GLYPHS.length} glyphs × ${FONT_VARIANTS.length} fonts = ${totalVariants} unique variants to ${outPath}`
);
console.log(`Mask size: ${MASK_W}x${MASK_H}, ~${Math.ceil((MASK_W * MASK_H) / 8)} bytes/glyph`);
