// scripts/generate-masks.ts
// Generate 1-bit packed glyph masks for server-side challenge rendering.
// Run with: npx tsx scripts/generate-masks.ts
//
// Uses @napi-rs/canvas (devDependency only — not needed at runtime).
// Output: server/glyph-masks.ts

import { writeFileSync } from 'fs';
import { resolve, dirname } from 'path';
import { fileURLToPath } from 'url';
import { createCanvas } from '@napi-rs/canvas';

const __dirname = dirname(fileURLToPath(import.meta.url));

const MASK_W = 64;
const MASK_H = 48;

// Same glyph set as CaptchaPage.tsx / handler.ts
const GLYPHS = [
  '2',
  '3',
  '4',
  '7',
  'A',
  'C',
  'E',
  'F',
  'H',
  'J',
  'K',
  'M',
  'N',
  'P',
  'R',
  'T',
  'W',
  'X',
  'Y',
];

function renderMask(char: string): string {
  const canvas = createCanvas(MASK_W, MASK_H);
  const ctx = canvas.getContext('2d');

  // Black background
  ctx.fillStyle = '#000';
  ctx.fillRect(0, 0, MASK_W, MASK_H);

  // White text — match the DotChallenge font style
  ctx.fillStyle = '#fff';
  ctx.font = `900 ${MASK_H * 0.72}px sans-serif`;
  ctx.textAlign = 'center';
  ctx.textBaseline = 'middle';
  ctx.fillText(char, MASK_W / 2, MASK_H / 2 + 1);

  const imageData = ctx.getImageData(0, 0, MASK_W, MASK_H);

  // Pack into 1-bit-per-pixel: each byte holds 8 pixels (MSB first)
  const totalPixels = MASK_W * MASK_H;
  const bytes = new Uint8Array(Math.ceil(totalPixels / 8));

  for (let i = 0; i < totalPixels; i++) {
    if (imageData.data[i * 4] > 128) {
      bytes[Math.floor(i / 8)] |= 1 << (7 - (i % 8));
    }
  }

  return Buffer.from(bytes).toString('base64');
}

// Generate all masks
const masks: Record<string, string> = {};
for (const g of GLYPHS) {
  masks[g] = renderMask(g);
}

// Output TypeScript file
const output = `// Auto-generated by scripts/generate-masks.ts — DO NOT EDIT
// ${MASK_W}x${MASK_H} 1-bit packed masks for glyph display (base64-encoded)
// Regenerate with: npx tsx scripts/generate-masks.ts

export const MASK_WIDTH = ${MASK_W};
export const MASK_HEIGHT = ${MASK_H};

/** Map from glyph character → base64-encoded 1-bit packed mask */
export const GLYPH_MASKS: Record<string, string> = ${JSON.stringify(masks, null, 2)};
`;

const outPath = resolve(__dirname, '../server/glyph-masks.ts');
writeFileSync(outPath, output, 'utf-8');
console.log(`Wrote ${Object.keys(masks).length} glyph masks to ${outPath}`);
console.log(`Mask size: ${MASK_W}x${MASK_H}, ~${Math.ceil((MASK_W * MASK_H) / 8)} bytes/glyph`);
